#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication $(getApplication)
#mpirun --allow-run-as-root -np 3 $(getApplication) -parallel  >> log.$(getApplication) 2>&1
#runApplication postProcess -func sampleDict

#------------------------------------------------------------------------------
