import sys
task,vvod = (sys.argv)
#print(vvod)
vvod = float(vvod)

calc_file = open("../postProcessing/sampleDict/0.25/line_U.csv")
calc2_file = open("../postProcessing/sampleDict/0.25/line_p_T_rho.csv")
res_file = open("./testSOD/exact.out")

stcl= calc_file.readline()
ndcl= calc2_file.readline()

file1= calc_file.readline()

file1_1= calc2_file.readline()
file2= res_file.readline()

a0,b0,c0,d0 = file1.split(",")
a0 = float(a0)
b0 = float(b0)
c0 = float(c0)
d0 = float(d0)
q0,r0,s0,z0 = file1_1.split(",")
q0=float(q0)
r0=float(r0)
s0=float(s0)
z0=float(z0)
k0,l0,m0,n0,p0 = file2.split(      )
k0=float(k0)
l0=float(l0)
m0=float(m0)
n0=float(n0)
p0=float(p0)

dx = abs(a0 - k0)
du = abs(b0 - m0)
dp = abs(r0 - n0)
dT = abs(s0 - p0)
drho = abs(z0 - l0)

file1 = calc_file.readline()

while file1 :
    a,b,c,d = file1.split(",")
    file1 = calc_file.readline()
    a=float(a)
    b=float(b)
    c=float(c)
    d=float(d)
    file1_1 = calc2_file.readline()
    q,r,s,z = file1_1.split(",")
    q=float(q)
    r=float(r)
    s=float(s)
    z=float(z)
    file2 = res_file.readline()
    k,l,m,n,p = file2.split(      )
    k=float(k)
    l=float(l)
    m=float(m)
    n=float(n)
    p=float(p)
    dx = dx + abs(a - k)
    du = du + abs(b - m)
    dp = dp + abs(r - n)
    dT = dT + abs(s - p)
    drho = drho + abs(z - l)
print("integral|x-x*|dx:")
dx = dx * vvod
print(dx)
print("integral|u-u*|dx:")
du = du * vvod
print(du)
print("integral|p-p*|dx:")
dp = dp * vvod
print(dp)
print("integral|T-T*|dx:")
dT = dT * vvod
print(dT)
print("integral|rho-rho*|dx:")
drho = drho * vvod
print(drho)
print("")

calc_file.close()
calc2_file.close()
res_file.close()
